defaults:
  - _self_

methods:
  - name: ASP
    path: data/asp/family_tree
  - name: ONT
    path: data/ont/family_tree
  - name: FC
    path: data/fc/family_tree

splits:
  - train
  - val
  - test

output:
  dir: reports/data_report
  save_plots: true
  merge_intermediate_into_inferred_for_plots: true
  top_k_predicates: 15
  ignore_predicates: []
  inferred_only: false

logging:
  level: INFO
