defaults:
  - config
  - override data/dataset: exp1_proof_based
  - _self_

model:
  embedding_size: 200
  num_hidden_layers: 2

callbacks:
  early_stopping:
    patience: 200
  model_checkpoint:
    filename: "best-checkpoint-proof_based"

logger:
  name: "exp1_proof_based_hpc"
  group: "exp1_negative_sampling"
  tags: [exp1, proof_based, hpc]
