defaults:
  - config
  - override data/dataset: exp1_mixed
  - _self_

callbacks:
  model_checkpoint:
    filename: "best-checkpoint-mixed"

logger:
  name: "exp1_mixed_hpc"
  group: "exp1_negative_sampling"
  tags: [exp1, mixed, hpc]
