defaults:
  - exp1_constrained_hpc
  - _self_

test:
  checkpoint_glob: "${log_dir}/checkpoints/best-checkpoint-constrained*.ckpt"

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: "${oc.env:WANDB_PROJECT, 'rrn-experiments'}"
  entity: "${oc.env:WANDB_ENTITY, null}"
  log_model: false
  save_dir: "${log_dir}"
  offline: false
  name: "exp1_constrained_hpc_test"
  group: "exp1_negative_sampling"
  tags: [exp1, constrained, hpc, test]
