defaults:
  - exp1_mixed_hpc
  - _self_

test:
  checkpoint_glob: "${oc.env:REPO_ROOT}/outputs/*/*/checkpoints/best-checkpoint-mixed*.ckpt"

logger:
  log_model: false
  name: "exp1_mixed_hpc_test"
  tags: [exp1, mixed, hpc, test]
