defaults:
  - exp1_random_hpc
  - _self_

test:
  checkpoint_glob: "${oc.env:REPO_ROOT}/outputs/*/*/checkpoints/best-checkpoint-random*.ckpt"

logger:
  log_model: false
  name: "exp1_random_hpc_test"
  tags: [exp1, random, hpc, test]
