defaults:
  - config
  - override data/dataset: exp1_random
  - _self_

callbacks:
  model_checkpoint:
    filename: "best-checkpoint-random"

logger:
  name: "exp1_random_hpc"
  group: "exp1_negative_sampling"
  tags: [exp1, random, hpc]
