defaults:
  - exp1_constrained_hpc
  - _self_

test:
  checkpoint_glob: "${oc.env:REPO_ROOT}/outputs/*/*/checkpoints/best-checkpoint-constrained*.ckpt"

logger:
  log_model: false
  name: "exp1_constrained_hpc_test"
  tags: [exp1, constrained, hpc, test]
