defaults:
  - exp1_proof_based_hpc
  - _self_

test:
  checkpoint_glob: "${oc.env:REPO_ROOT}/outputs/*/*/checkpoints/best-checkpoint-proof_based*.ckpt"

logger:
  log_model: false
  name: "exp1_proof_based_hpc_test"
  tags: [exp1, proof_based, hpc, test]
