defaults:
  - config
  - override data/dataset: exp1_constrained
  - _self_

hyperparams:
  learning_rate: 0.0001

callbacks:
  early_stopping:
    patience: 200
  model_checkpoint:
    filename: "best-checkpoint-constrained"

logger:
  name: "exp1_constrained_hpc"
  group: "exp1_negative_sampling"
  tags: [exp1, constrained, hpc]
