defaults:
  - config
  - override data/dataset: exp2_synthology
  - _self_

callbacks:
  model_checkpoint:
    filename: "best-checkpoint-exp2-synthology"

logger:
  name: "exp2_synthology_hpc"
  group: "exp2_multihop"
  tags: [exp2, synthology, hpc]
