defaults:
  - config
  - override data/dataset: exp2_baseline
  - _self_

callbacks:
  model_checkpoint:
    filename: "best-checkpoint-exp2-baseline"

logger:
  name: "exp2_baseline_hpc"
  group: "exp2_multihop"
  tags: [exp2, baseline, hpc]
