defaults:
  - exp3_owl2bench_hpc
  - _self_

data:
  train_path: "data/exp3/balanced/owl2bench_5/train"
  val_path: "data/exp3/balanced/owl2bench_5/val"
  test_path: "data/exp3/balanced/owl2bench_5/test"

logger:
  name: "exp3_synthology_owl2bench_u5_hpc"
  group: "exp3_scaling"
  tags: [exp3, synthology, owl2bench, u5, hpc]
