# See config.yaml for more details about all configuration options.
# The README file also contains further details.

defaults:
  - config # override default config options
  - _self_

seed: 46 # distinct from training seed

dataset:
  output_dir: "data/exp1/test_set"
  n_train: 0
  n_val: 0
  n_test: 500

hydra:
  run:
    dir: "${dataset.output_dir}/hydra"

neg_sampling:
  strategy: "mixed"
  corrupt_base_facts: true
  mixed_weights:
    proof_based: 0.5
    constrained: 0.5
    random: 0.0
    type_aware: 0.0

generator:
  min_lcc_ratio: 0.6
