# See config.yaml for more details about all configuration options.
# The README file also contains further details.

defaults:
  - exp1_base # override default config options
  - _self_

dataset:
  output_dir: "data/exp1/proof_based"

neg_sampling:
  strategy: "proof_based"
  corrupt_base_facts: true
