# See config.yaml for full documentation of all options.
# Only overrides from config.yaml defaults are listed here.

defaults:
  - exp1_base # override default config options
  - _self_

seed: 42 # different from train seed

dataset:
  n_train: 0
  n_val: 0
  n_test: 350
  output_dir: "data/exp2/frozen_test"

  # favor deep proofs for test set
  proof_selection_strategy: "stratified"
  proof_selection_weights:
    easy: 2
    medium: 40
    hard: 60

neg_sampling:
  strategy: "mixed"
  corrupt_base_facts: true
  mixed_weights:
    proof_based: 0.5
    constrained: 0.5
    random: 0.0
    type_aware: 0.0
