defaults:
  - exp1_base # override default config options
  - _self_

dataset:
  n_train: 2000
  n_val: 500
  n_test: 0
  train_fact_cap: 400000
  output_dir: "data/exp2/synthology/family_tree"

neg_sampling:
  strategy: "mixed"
  corrupt_base_facts: true
  mixed_weights:
    proof_based: 0.5
    constrained: 0.5
    random: 0.0
    type_aware: 0.0
