learning_rate: 0.001
optimizer:
  _target_: torch.optim.Adam
  lr: ${hyperparams.learning_rate}
  weight_decay: ${hyperparams.weight_decay}
batch_size: 16
weight_decay: 0.000001 # 10^-6 as in the paper
eval_every: 10
early_stopping_patience: 10
