#!/usr/bin/env bash

#BSUB -q hpc
#BSUB -J exp3-generate-baseline
#BSUB -n 8
#BSUB -W 24:00
#BSUB -R "rusage[mem=96GB]"
#BSUB -o logs/exp3_generate_baseline_%J.out
#BSUB -e logs/exp3_generate_baseline_%J.err

export MAVEN_HOME="apache-maven-3.9.13"
export PATH="${MAVEN_HOME}/bin:${PATH}"

set -euo pipefail
mkdir -p logs

# Override these at submit time if needed, e.g.:
# UNIVERSITIES=1 SYNTHOLOGY_UDM_BASELINE_XMX_MB=57344 bsub < jobscripts/exp3-generate-baseline.sh
UNIVERSITIES="${UNIVERSITIES:-1}"
SYNTHOLOGY_UDM_BASELINE_XMX_MB="${SYNTHOLOGY_UDM_BASELINE_XMX_MB:-57344}"
SYNTHOLOGY_JENA_XMX_MB="${SYNTHOLOGY_JENA_XMX_MB:-${SYNTHOLOGY_UDM_BASELINE_XMX_MB}}"
SYNTHOLOGY_HEAP_MB="${SYNTHOLOGY_HEAP_MB:-${SYNTHOLOGY_UDM_BASELINE_XMX_MB}}"
SYNTHOLOGY_EXP3_REASONING_INPUT_TRIPLE_CAP="${SYNTHOLOGY_EXP3_REASONING_INPUT_TRIPLE_CAP:-1200}"
SYNTHOLOGY_EXP3_ABOX_JENA_XMX_MB="${SYNTHOLOGY_EXP3_ABOX_JENA_XMX_MB:-8192}"
SYNTHOLOGY_EXP3_FINAL_REASONING_INPUT_TRIPLE_CAP="${SYNTHOLOGY_EXP3_FINAL_REASONING_INPUT_TRIPLE_CAP:-15000}"
SYNTHOLOGY_EXP3_FINAL_JENA_PROFILE="${SYNTHOLOGY_EXP3_FINAL_JENA_PROFILE:-owl_mini}"

if command -v module >/dev/null 2>&1; then
  module load python3/3.9.19 || true
  module load openjdk/21 || true
fi

export MAVEN_HOME="${MAVEN_HOME:-apache-maven-3.9.13}"
export PATH="${MAVEN_HOME}/bin:${PATH}"
export MAVEN_EXECUTABLE="${MAVEN_EXECUTABLE:-${MAVEN_HOME}/bin/mvn}"
export MAVEN_REPO_LOCAL="${MAVEN_REPO_LOCAL:-/dtu/blackhole/16/221590/.m2/repository}"
mkdir -p "${MAVEN_REPO_LOCAL}"

# Keep baseline heap sizing explicit and aligned across wrappers.
export SYNTHOLOGY_UDM_BASELINE_XMX_MB
export SYNTHOLOGY_JENA_XMX_MB
export SYNTHOLOGY_HEAP_MB
export SYNTHOLOGY_EXP3_REASONING_INPUT_TRIPLE_CAP
export SYNTHOLOGY_EXP3_ABOX_JENA_XMX_MB
export SYNTHOLOGY_EXP3_FINAL_REASONING_INPUT_TRIPLE_CAP
export SYNTHOLOGY_EXP3_FINAL_JENA_PROFILE

source .venv/bin/activate
uv sync

echo "Starting Exp3 baseline generation"
echo "  universities=${UNIVERSITIES}"
echo "  SYNTHOLOGY_UDM_BASELINE_XMX_MB=${SYNTHOLOGY_UDM_BASELINE_XMX_MB}"
echo "  SYNTHOLOGY_EXP3_REASONING_INPUT_TRIPLE_CAP=${SYNTHOLOGY_EXP3_REASONING_INPUT_TRIPLE_CAP}"
echo "  SYNTHOLOGY_EXP3_ABOX_JENA_XMX_MB=${SYNTHOLOGY_EXP3_ABOX_JENA_XMX_MB}"
echo "  SYNTHOLOGY_EXP3_FINAL_REASONING_INPUT_TRIPLE_CAP=${SYNTHOLOGY_EXP3_FINAL_REASONING_INPUT_TRIPLE_CAP}"
echo "  SYNTHOLOGY_EXP3_FINAL_JENA_PROFILE=${SYNTHOLOGY_EXP3_FINAL_JENA_PROFILE}"
echo "  MAVEN_EXECUTABLE=${MAVEN_EXECUTABLE}"
echo "  MAVEN_REPO_LOCAL=${MAVEN_REPO_LOCAL}"

uv run invoke exp3-generate-baseline --universities="${UNIVERSITIES}"

echo "Finished Exp3 baseline generation at:"
date
