#!/usr/bin/env bash
# Exp3 scalability sweep launcher.
#
# Run from the repo root (NOT via bsub):
#   bash jobscripts/exp3-scalability-launch.sh [--dry-run]
#
# For each u in U_VALUES it:
#   1. Writes configs/experiments/scalability/exp3_scale_u{N}.yaml
#   2. Generates jobscripts/scalability/bl_u{N}.sh  (baseline generation)
#   3. Submits the baseline job, captures job ID
#   4. Generates jobscripts/scalability/sb_u{N}.sh  (synthology + balance,
#      depends on the baseline job finishing successfully)
#   5. Submits the synthology+balance job
#
# Each job writes a one-line result to results/exp3_scalability/u{N}_{method}.csv:
#   U,method,time_sec,mem_mb,status
#
# After all jobs complete, run:
#   bash jobscripts/exp3-scalability-collect.sh
# to assemble results/exp3_scalability/timing_summary.csv for MATLAB.
#
# Memory model (owl_full, no triple cap):
#   Measured: u=5 → 14.8 GB,  u=14 → 107.5 GB
#   Fit: mem ≈ 14.8 × (u/5)^1.9  ← super-linear but sub-quadratic
#   Requests below include a ≥25% safety margin.

set -euo pipefail

DRY_RUN=0
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1

if [ -f "${PWD}/jobscripts/common.sh" ]; then
	REPO_ROOT="${PWD}"
elif [ -n "${LS_SUBCWD:-}" ] && [ -f "${LS_SUBCWD}/jobscripts/common.sh" ]; then
	REPO_ROOT="${LS_SUBCWD}"
else
	SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
fi

RESULTS_DIR="${REPO_ROOT}/results/exp3_scalability"
CONFIGS_DIR="${REPO_ROOT}/configs/experiments/scalability"
JOBS_DIR="${REPO_ROOT}/jobscripts/scalability"
mkdir -p "${RESULTS_DIR}" "${CONFIGS_DIR}" "${JOBS_DIR}" "${REPO_ROOT}/logs"

# ── Resource table for baseline (Jena owl_full, no triple cap) ───────────────
# mem = GB per LSF slot (8 slots × mem = total node memory)
# heap = Jena JVM max heap in MB (≈85% of total reserved memory)
# wall = HH:MM  (generous; based on measured u=5→12.6 min, u=14→1130 min,
#                scaling exponent ≈4.4; values below include 1.4× headroom)
U_VALUES=(2 4 6 8 10 12 14)

declare -A BL_MEM BL_HEAP BL_WALL
# Uniform 100 GB heap for all u — same fixed hardware budget for a fair comparison.
# Jobs that complete give real wall-clock time; jobs that OOM fail at the natural
# ceiling (not an artificial per-u limit).  u=14 is expected to OOM (~107 GB needed).
# LSF: 100 GB heap + ~12 GB JVM/OS overhead = ~112 GB → 14 GB/slot × 8 slots.
BL_MEM[2]=14;  BL_HEAP[2]=100000;  BL_WALL[2]="24:00"
BL_MEM[4]=14;  BL_HEAP[4]=100000;  BL_WALL[4]="24:00"
BL_MEM[6]=14;  BL_HEAP[6]=100000;  BL_WALL[6]="24:00"
BL_MEM[8]=14;  BL_HEAP[8]=100000;  BL_WALL[8]="24:00"
BL_MEM[10]=14; BL_HEAP[10]=100000; BL_WALL[10]="24:00"
BL_MEM[12]=14; BL_HEAP[12]=100000; BL_WALL[12]="24:00"
BL_MEM[14]=14; BL_HEAP[14]=100000; BL_WALL[14]="24:00"

_submit() {
	# Usage: _submit <script_path>
	# Returns the LSF job ID on stdout, or "" on failure.
	local jid
	jid=$(bsub < "${1}" 2>&1 | sed -n 's/.*Job <\([0-9]*\)>.*/\1/p')
	echo "${jid}"
}

echo "================================================================"
echo "  Exp3 scalability sweep — u = ${U_VALUES[*]}"
echo "  Results dir : ${RESULTS_DIR}"
echo "  Configs dir : ${CONFIGS_DIR}"
echo "  Jobs dir    : ${JOBS_DIR}"
[ "${DRY_RUN}" -eq 1 ] && echo "  *** DRY RUN — no jobs will be submitted ***"
echo "================================================================"
echo ""

for U in "${U_VALUES[@]}"; do
	CONFIG="${CONFIGS_DIR}/exp3_scale_u${U}.yaml"
	DATA_ROOT="data/exp3_scale/u${U}"
	BL_JOB="${JOBS_DIR}/bl_u${U}.sh"
	SB_JOB="${JOBS_DIR}/sb_u${U}.sh"

	# ── 1. Write per-u YAML config ─────────────────────────────────────────
	cat > "${CONFIG}" << YAML
# Auto-generated by exp3-scalability-launch.sh — do not edit by hand.
universities: ${U}

baseline:
  reasoning_input_triple_cap: 0
  abox_jena_heap_mb: ${BL_HEAP[${U}]}
  # Route OWL2Bench output to a per-u directory so parallel jobs don't clobber.
  args: "dataset.output_dir=${DATA_ROOT}/owl2bench/output"

synthology:
  output_dir: "${DATA_ROOT}/synthology/owl2bench"
  args: ""

balance:
  baseline_dir: "${DATA_ROOT}/owl2bench/output/owl2bench"
  synthology_dir: "${DATA_ROOT}/synthology/owl2bench"
  output_dir: "${DATA_ROOT}/balanced/owl2bench"
  baseline_output_dir: "${DATA_ROOT}/balanced_baseline/owl2bench"
  seed: 23
YAML

	# ── 2. Generate baseline job script ────────────────────────────────────
	# Header: #BSUB directives and baked-in path variables (expanded now)
	cat > "${BL_JOB}" << HEADER
#!/usr/bin/env bash
#BSUB -q hpc
#BSUB -J exp3-scale-bl-u${U}
#BSUB -n 8
#BSUB -W ${BL_WALL[${U}]}
#BSUB -R "rusage[mem=${BL_MEM[${U}]}GB] span[hosts=1]"
#BSUB -o ${REPO_ROOT}/logs/exp3_scale_bl_u${U}_%J.out
#BSUB -e ${REPO_ROOT}/logs/exp3_scale_bl_u${U}_%J.err

# Baked-in parameters (set at script-generation time by the launcher)
REPO_ROOT="${REPO_ROOT}"
SCALE_U="${U}"
SCALE_CONFIG="${CONFIG}"
SCALE_RESULTS_DIR="${RESULTS_DIR}"
HEADER

	# Body: literal bash evaluated at job run time (single-quoted heredoc)
	cat >> "${BL_JOB}" << 'BODY'
set -uo pipefail

. "${REPO_ROOT}/jobscripts/common.sh"
synthology_enter_repo
synthology_setup_runtime_storage
mkdir -p logs

synthology_load_modules python3/3.9.19 openjdk/21

export MAVEN_HOME="apache-maven-3.9.13"
export PATH="${MAVEN_HOME}/bin:${PATH}"
export MAVEN_EXECUTABLE="${MAVEN_HOME}/bin/mvn"
export MAVEN_REPO_LOCAL="/dtu/blackhole/16/221590/.m2/repository"
mkdir -p "${MAVEN_REPO_LOCAL}"

synthology_activate_python_env 0
synthology_sync_deps

RESULT_FILE="${SCALE_RESULTS_DIR}/u${SCALE_U}_baseline.csv"
TIME_FILE="${SCALE_RESULTS_DIR}/u${SCALE_U}_baseline_time.txt"

echo "==================================================================="
echo "  Exp3 scalability: BASELINE  u=${SCALE_U}"
echo "  Config : ${SCALE_CONFIG}"
echo "==================================================================="

START=$(date +%s)
STATUS="OK"

set +e
/usr/bin/time -v -o "${TIME_FILE}" \
	uv run invoke exp3-generate-baseline-hpc --config-path="${SCALE_CONFIG}"
RC=$?
set -e

END=$(date +%s)
ELAPSED=$((END - START))

if [ "${RC}" -ne 0 ]; then
	STATUS="FAILED_RC${RC}"
	echo "ERROR: baseline u=${SCALE_U} exited with code ${RC} — result marked FAILED"
fi

MEM_MB=0
if [ -f "${TIME_FILE}" ]; then
	MEM_KB=$(grep -oP "(?<=Maximum resident set size \(kbytes\): )\d+" "${TIME_FILE}" 2>/dev/null || echo 0)
	[ "${MEM_KB:-0}" -gt 0 ] && MEM_MB=$((MEM_KB / 1024))
fi

printf '%s,baseline,%d,%d,%s\n' "${SCALE_U}" "${ELAPSED}" "${MEM_MB}" "${STATUS}" \
	> "${RESULT_FILE}"

echo ""
echo "SCALE_RESULT u=${SCALE_U} method=baseline time_sec=${ELAPSED} mem_mb=${MEM_MB} status=${STATUS}"
echo "Finished at:"; date
BODY
	chmod +x "${BL_JOB}"

	# ── 3. Submit baseline job ──────────────────────────────────────────────
	if [ "${DRY_RUN}" -eq 1 ]; then
		BL_JID="DRY_RUN_BL_U${U}"
		echo "u=${U}  [dry-run] baseline job: ${BL_JOB}"
	else
		BL_JID=$(_submit "${BL_JOB}")
		echo "u=${U}  baseline job submitted → ${BL_JID:-SUBMIT_FAILED}"
	fi

	# ── 4. Generate synthology+balance job script ───────────────────────────
	# Depends on the baseline job completing successfully (-w "done(JID)").
	cat > "${SB_JOB}" << HEADER
#!/usr/bin/env bash
#BSUB -q hpc
#BSUB -J exp3-scale-sb-u${U}
#BSUB -w "done(${BL_JID})"
#BSUB -n 8
#BSUB -W 04:00
#BSUB -R "rusage[mem=2GB]"
#BSUB -o ${REPO_ROOT}/logs/exp3_scale_sb_u${U}_%J.out
#BSUB -e ${REPO_ROOT}/logs/exp3_scale_sb_u${U}_%J.err

# Baked-in parameters
REPO_ROOT="${REPO_ROOT}"
SCALE_U="${U}"
SCALE_CONFIG="${CONFIG}"
SCALE_RESULTS_DIR="${RESULTS_DIR}"
HEADER

	cat >> "${SB_JOB}" << 'BODY'
set -uo pipefail

. "${REPO_ROOT}/jobscripts/common.sh"
synthology_enter_repo
synthology_setup_runtime_storage
mkdir -p logs

synthology_load_modules python3/3.9.19 openjdk/21

export MAVEN_HOME="apache-maven-3.9.13"
export PATH="${MAVEN_HOME}/bin:${PATH}"
export MAVEN_EXECUTABLE="${MAVEN_HOME}/bin/mvn"
export MAVEN_REPO_LOCAL="/dtu/blackhole/16/221590/.m2/repository"
mkdir -p "${MAVEN_REPO_LOCAL}"

synthology_activate_python_env 0
synthology_sync_deps

RESULT_FILE="${SCALE_RESULTS_DIR}/u${SCALE_U}_synthology.csv"
TIME_FILE="${SCALE_RESULTS_DIR}/u${SCALE_U}_synthology_time.txt"

echo "==================================================================="
echo "  Exp3 scalability: SYNTHOLOGY  u=${SCALE_U}"
echo "  Config : ${SCALE_CONFIG}"
echo "==================================================================="

START=$(date +%s)
STATUS="OK"

set +e
/usr/bin/time -v -o "${TIME_FILE}" \
	uv run invoke exp3-generate-synthology-hpc --config-path="${SCALE_CONFIG}"
RC=$?
set -e

END=$(date +%s)
ELAPSED=$((END - START))

if [ "${RC}" -ne 0 ]; then
	STATUS="FAILED_RC${RC}"
	echo "ERROR: synthology u=${SCALE_U} exited with code ${RC} — result marked FAILED"
fi

MEM_MB=0
if [ -f "${TIME_FILE}" ]; then
	MEM_KB=$(grep -oP "(?<=Maximum resident set size \(kbytes\): )\d+" "${TIME_FILE}" 2>/dev/null || echo 0)
	[ "${MEM_KB:-0}" -gt 0 ] && MEM_MB=$((MEM_KB / 1024))
fi

printf '%s,synthology,%d,%d,%s\n' "${SCALE_U}" "${ELAPSED}" "${MEM_MB}" "${STATUS}" \
	> "${RESULT_FILE}"

echo ""
echo "SCALE_RESULT u=${SCALE_U} method=synthology time_sec=${ELAPSED} mem_mb=${MEM_MB} status=${STATUS}"

# ── Balance step (only runs if synthology succeeded) ──────────────────────
if [ "${STATUS}" = "OK" ]; then
	echo ""
	echo "==================================================================="
	echo "  Exp3 scalability: BALANCE  u=${SCALE_U}"
	echo "==================================================================="
	set +e
	uv run invoke exp3-balance-data-hpc --config-path="${SCALE_CONFIG}"
	BALANCE_RC=$?
	set -e
	if [ "${BALANCE_RC}" -ne 0 ]; then
		echo "WARNING: balance step failed with exit code ${BALANCE_RC}"
	fi
fi

echo "Finished at:"; date
BODY
	chmod +x "${SB_JOB}"

	# ── 5. Submit synthology+balance job ───────────────────────────────────
	if [ "${DRY_RUN}" -eq 1 ]; then
		echo "u=${U}  [dry-run] synthology+balance job: ${SB_JOB} (after ${BL_JID})"
	else
		SB_JID=$(_submit "${SB_JOB}")
		echo "u=${U}  synthology+balance job submitted → ${SB_JID:-SUBMIT_FAILED}"
	fi
	echo ""
done

echo "================================================================"
echo "  All jobs submitted."
echo "  Monitor  : bjobs"
echo "  Collect  : bash jobscripts/exp3-scalability-collect.sh"
echo "  Visualise: matlab/exp3_scalability.m  (after collect)"
echo "================================================================"
